### ISSUE TITLE
archivetar does not request required scopes on auth

### ISSUE THREAD

**Issue by theAeon** [brockpalen/archivetar#31]
Getting ```403, 'ConsentRequired', 'Missing required data_access consent'``` since the umich#flux depreciation. Seems to be that the new "Non-Sensitive Data-Den" volume needs data_access explicitly requested.

Per https://github.com/globus/globus-sdk-python/issues/638 this seems to be an easy fix.

**Comment by brockpalen** [comment]
This should now be fixed in  v0.15.0

This addresses a change in the auth model for Globus V5 servers it does not impact globus connect personnel.

It will impact a few changes in behavior:

1. Even if you have used an endpoint/collection before if it's upgraded to GCS5 you will have to login again
2. Every time you use a new GCS5 server you will have to login to expcitly give the token that archivetar users permission to talk to that server
3. `--destination` and `--source` must now be the UUID and not the friendly name.  

For 3 I'm Interested in ideas.  Globus does provide [endpoint_search()](https://globus-sdk-python.readthedocs.io/en/stable/services/transfer.html#globus_sdk.TransferClient.endpoint_search) though Globus has kinda made a mess of the endpoint vs collections where in GCS5 endpoint is not the same thing as GCS4 and sometimes the APIs are misleading.

Still if there was a search what would people want to see?  Something like:

```
if destination is not UUID:
   endpoint_search(destination, limit=1)
```

and just use the first one and assume it's correct?

**Comment by theAeon** [comment]
Appreciate it! I wouldn't assume that the first result is correct because there's no guarantee that it'll be the same from run to run (and, in theory, that could even be a security issue!) If you're taking that approach, you absolutely need to prompt on first use and cache the GUID.

Not sure there's any other good way to do friendly names at all, for what its worth.

**Comment by brockpalen** [comment]
I'm closing this out and moved the discussion to a new issue for ideas to make UUIDs more user friendly
